import java.awt.Font;
import java.awt.font.TextAttribute;
import javax.swing.JOptionPane;
import javax.swing.text.*;
import java.io.*;
import java.util.Map;

public class Editor extends javax.swing.JFrame 
{
    StringBuffer sbuffer = new StringBuffer();
    String rutaArchivo;
    String carpetaArchivos = "C:\\Users\\Anselmo\\Documents\\NetBeansProjects\\PracticaEditor\\ArchivosTexto";
    String ruta0 = "";
    String ruta1 = "";
    String ruta2 = "";
    int indiceFocus;
    
    public Editor() 
    {
        initComponents();
    }
    
    javax.swing.JEditorPane TabDisponible()
    {
        javax.swing.JEditorPane panelDisponible = null;
        if(jEditorPane1.getText().equals(""))
        {
            panelDisponible = jEditorPane1;
            indiceFocus = 0;
        }
        else if(jEditorPane3.getText().equals(""))
        {
            panelDisponible = jEditorPane3;
            indiceFocus = 1;
        }
        else if(jEditorPane4.getText().equals(""))
        {
            panelDisponible = jEditorPane4;
            indiceFocus = 2;
        }
        return panelDisponible;
    }
    
    javax.swing.JEditorPane PanelSeleccionado()
    {
        javax.swing.JEditorPane panelDisponible = null;
        if(jEditorPane1.isShowing())
        {
            panelDisponible = jEditorPane1;
            indiceFocus = 0;
        }
        else if(jEditorPane3.isShowing())
        {
            panelDisponible = jEditorPane3;
            indiceFocus = 1;
        }
        else if(jEditorPane4.isShowing())
        {
            panelDisponible = jEditorPane4;
            indiceFocus = 2;
        }
        return panelDisponible;
    }

    void EscribeRuta(File file)
    {
        if(indiceFocus == 0)
        {
            ruta0 = file.getAbsolutePath();
        }
        else if(indiceFocus == 1)
        {
            ruta1 = file.getAbsolutePath();
        }
        else if(indiceFocus == 2)
        {
            ruta2 = file.getAbsolutePath();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jEditorPane3 = new javax.swing.JEditorPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jEditorPane4 = new javax.swing.JEditorPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setViewportView(jEditorPane1);

        jTabbedPane1.addTab("tab1", jScrollPane2);

        jScrollPane3.setViewportView(jEditorPane3);

        jTabbedPane1.addTab("tab2", jScrollPane3);

        jScrollPane4.setViewportView(jEditorPane4);

        jTabbedPane1.addTab("tab3", jScrollPane4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addGap(58, 58, 58))
        );

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Abrir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Guardar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Cuardar como");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Salir");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edicion");

        jMenuItem5.setText("Negrita");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Cursiva");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Subrayado");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Acerca de");

        jMenuItem8.setText("Informacion");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Guardar Como
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        int rVal = jFileChooser1.showSaveDialog(this);
        if (rVal == jFileChooser1.APPROVE_OPTION) 
        {
            File guardar = jFileChooser1.getSelectedFile();
            try
            {
                try(FileWriter fw = new FileWriter(jFileChooser1.getSelectedFile() + ".txt")) 
                {
                    fw.write(jFileChooser1.getName(guardar).toString());
                }
            } 
            catch (Exception ex) 
            {
                ex.printStackTrace();
            }
        }
        
        /*javax.swing.JEditorPane panel = PanelSeleccionado();
        String nombreArchivo = JOptionPane.showInputDialog(this, "Ingrese el nombre del archivo:");
        try 
        {
            FileWriter escritura = new FileWriter(carpetaArchivos + "\\" + nombreArchivo + ".txt", true);
            escritura.write(panel.getText());
            escritura.close();
        } 
        catch (IOException ex) 
        {
            ex.printStackTrace();
        }*/
    }//GEN-LAST:event_jMenuItem3ActionPerformed
    //Salir
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
       dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed
    //Guardar
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        javax.swing.JEditorPane panel = PanelSeleccionado();
        String ruta = "";
        
        if(indiceFocus == 0)
            ruta = ruta0;
        else if(indiceFocus == 1)
            ruta = ruta1;
        else if(indiceFocus == 2)
            ruta = ruta2;
        
        String texto = panel.getText();
        try 
        {
            FileWriter escritura = new FileWriter(ruta, false);
            escritura.write(texto);
            escritura.close();
        } 
        catch (IOException ex) 
        {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    //Abrir
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        javax.swing.JEditorPane panelDisponible = TabDisponible();
        if(panelDisponible != null)
        {
            int returnVal = jFileChooser1.showOpenDialog(this);
            if (returnVal == jFileChooser1.APPROVE_OPTION) 
            {
                File file = jFileChooser1.getSelectedFile();
                EscribeRuta(file);
                try 
                {
                    panelDisponible.read(new FileReader(file.getAbsolutePath()), null);
                    jTabbedPane1.setSelectedIndex(indiceFocus);
                    /*FileReader fileOpen = new FileReader(filePath);
                    BufferedReader entrada = new BufferedReader(fileOpen);
                     while (entrada.ready()) 
                    {
                        String next_line = entrada.readLine();
                        next_line = next_line + "\r\n";
                        sbuffer.append(next_line);
                    }
                    entrada.close();
                    panelDisponible.setText(sbuffer.toString());*/
                }
                catch (IOException ex) 
                {
                    System.out.println("No se puedo acceder a " + file.getAbsolutePath());
                }
            } 
        }
        else
        {
            JOptionPane.showMessageDialog(this, "No puede abrir mas archivos.");
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    //Negrita
    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        javax.swing.JEditorPane panel = PanelSeleccionado();
        panel.setFont(new Font("Arial", Font.BOLD, 12));
    }//GEN-LAST:event_jMenuItem5ActionPerformed
    //Cursiva
    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        javax.swing.JEditorPane panel = PanelSeleccionado();
        panel.setFont(new Font("Arial", Font.ITALIC, 12));
    }//GEN-LAST:event_jMenuItem6ActionPerformed
    //Subrayado
    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        javax.swing.JEditorPane panel = PanelSeleccionado();
        Font font = panel.getFont();
        Map atributos = font.getAttributes();
        atributos.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        panel.setFont(font.deriveFont(atributos));
    }//GEN-LAST:event_jMenuItem7ActionPerformed
    //Informacion
    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        JOptionPane.showMessageDialog(jPanel2, "Practica Editor de Texto.\r\nProgramacion. 1TV7.\r\nAlvardo Balbuena Jorge Anselmo");
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JEditorPane jEditorPane3;
    private javax.swing.JEditorPane jEditorPane4;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
